# Generated by Django 3.0.6 on 2020-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouterDetails',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('sapid', models.CharField(max_length=18, unique=True)),
                ('hostname', models.CharField(max_length=14, unique=True)),
                ('loopbackid', models.CharField(max_length=15)),
                ('mac_add', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
