# Generated by Django 3.0.6 on 2020-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdetail', '0004_auto_20201003_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='loopbackid',
            field=models.CharField(max_length=150),
        ),
    ]
